"""
AYX Limited Laundry App -- FastAPI MVP entrypoint.

Run locally with:
    uvicorn app.main:app --reload

Interactive API docs (auto-generated by FastAPI) will be available at:
    http://localhost:8000/docs
"""

from fastapi import FastAPI

from app.database import Base, engine
from app.routers import users, subscriptions, orders, admin, stripe_webhook

# For the MVP we create tables directly from the models at startup.
# For anything beyond MVP, switch to Alembic migrations so schema changes
# are versioned instead of just "whatever the models currently say".
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="AYX Limited Laundry App",
    description="MVP subscription-based laundry pickup & delivery service.",
    version="0.1.0",
)

app.include_router(users.router)
app.include_router(subscriptions.router)
app.include_router(orders.router)
app.include_router(admin.router)
app.include_router(stripe_webhook.router)


@app.get("/")
def root():
    return {"status": "ok", "service": "AYX Laundry MVP"}


@app.get("/health")
def health():
    return {"status": "healthy"}
